name: Super-Linter-Code

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup PHP
            uses:Administrator/setup-php@v2
            with:
              php-version: '8.2' # Specify your desired PHP version
              extensions: mbstring, pdo_mysql, zip
              tools: composer
              
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
